export const TRANSACTION_LIST_REQUEST = "TRANSACTION_LIST_REQUEST";
export const TRANSACTION_LIST_SUCCESS = "TRANSACTION_LIST_SUCCESS";
export const TRANSACTION_LIST_FAIL = "TRANSACTION_LIST_FAIL";
export const TRANSACTION_LIST_RESET = "TRANSACTION_LIST_RESET";

export const TRANSACTION_DETAILS_REQUEST = "TRANSACTION_DETAILS_REQUEST";
export const TRANSACTION_DETAILS_SUCCESS = "TRANSACTION_DETAILS_SUCCESS";
export const TRANSACTION_DETAILS_FAIL = "TRANSACTION_DETAILS_FAIL";

export const TRANSACTION_DELETE_REQUEST = "TRANSACTION_DELETE_REQUEST";
export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";
export const TRANSACTION_DELETE_FAIL = "TRANSACTION_DELETE_FAIL";

export const TRANSACTION_CREATE_REQUEST = "TRANSACTION_CREATE_REQUEST";
export const TRANSACTION_CREATE_SUCCESS = "TRANSACTION_CREATE_SUCCESS";
export const TRANSACTION_CREATE_FAIL = "TRANSACTION_CREATE_FAIL";
export const TRANSACTION_CREATE_RESET = "TRANSACTION_CREATE_RESET";

export const TRANSACTION_UPDATE_REQUEST = "TRANSACTION_UPDATE_REQUEST";
export const TRANSACTION_UPDATE_SUCCESS = "TRANSACTION_UPDATE_SUCCESS";
export const TRANSACTION_UPDATE_FAIL = "TRANSACTION_UPDATE_FAIL";
export const TRANSACTION_UPDATE_RESET = "TRANSACTION_UPDATE_RESET";
